name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      # Add your additional steps here, such as installing dependencies and running tests.
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Replace with your actual command

      - name: Run tests
        run: |
          python -m unittest discover  # Replace with your actual test command
